import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'getting-started',
      label: 'Getting Started',
    },
    {
      type: 'category',
      label: 'Applications',
      collapsed: false,
      items: [
        'apps/nova',
        'apps/nova-gfx',
        'apps/pulsar-gfx',
      ],
    },
    {
      type: 'category',
      label: 'Nova Features',
      collapsed: true,
      items: [
        'nova/elections',
        'nova/finance',
        'nova/sports',
        'nova/weather',
        'nova/news',
        'nova/agents',
        'nova/media',
        'nova/graphics',
        'nova/data-sources',
        'nova/permissions',
        'nova/overrides',
      ],
    },
    {
      type: 'category',
      label: 'Nova GFX Features',
      collapsed: false,
      items: [
        'features/layers',
        'features/preview',
        'features/publishing',
        'features/ai-assistant',
        'features/ai-configuration',
        'features/design-guidelines',
        'features/project-settings',
        'features/auto-follow',
        'features/properties-search',
      ],
    },
    {
      type: 'category',
      label: 'Pulsar GFX Features',
      collapsed: false,
      items: [
        'features/pulsar-playlist',
        'features/pulsar-loop',
        'features/pulsar-preview',
        'features/pulsar-channels',
      ],
    },
    {
      type: 'category',
      label: 'Elements',
      collapsed: true,
      items: [
        'elements/overview',
        'elements/text',
        'elements/image',
        'elements/shape',
        'elements/line',
        'elements/video',
        'elements/map',
        'elements/chart',
        'elements/ticker',
        'elements/topic-badge',
        'elements/icon',
        'elements/svg',
        'elements/table',
        'elements/countdown',
        'elements/lottie',
        'elements/group',
      ],
    },
    {
      type: 'category',
      label: 'Animation',
      collapsed: true,
      items: [
        'animation/overview',
        'animation/timeline',
        'animation/phases',
        'animation/keyframes',
        'animation/easing',
        'animation/presets',
        'animation/character-animation',
      ],
    },
    {
      type: 'category',
      label: 'Templates',
      collapsed: true,
      items: [
        'templates/overview',
        'templates/creating',
        'templates/layers',
        'templates/content-fields',
      ],
    },
    {
      type: 'category',
      label: 'Integration',
      collapsed: true,
      items: [
        'integration/obs',
        'integration/vmix',
        'integration/api',
        'integration/data-sources',
      ],
    },
  ],
  apiSidebar: [
    {
      type: 'doc',
      id: 'api/overview',
      label: 'API Overview',
    },
    {
      type: 'category',
      label: 'REST API',
      items: [
        'api/rest/authentication',
        'api/rest/projects',
        'api/rest/templates',
        'api/rest/elements',
        'api/rest/pages',
      ],
    },
    {
      type: 'category',
      label: 'Types',
      items: [
        'api/types/element',
        'api/types/template',
        'api/types/animation',
        'api/types/content',
      ],
    },
  ],
};

export default sidebars;
